### ISSUE TITLE
Is the dependence on ipywidgets required? 

### ISSUE THREAD

**Issue by jan-janssen** [conda-forge/pyscal-feedstock#53]
### Comment:

Hi @srmnitc , 

As `pyiron_atomistics` now depends on `pyscal` it would be great to have `ipywidgets` as optional dependency to decrease the overall size of the `pyiron_atomistics` installation. Now either `pyiron_atomistics` could have `pyscal` as optional requirement or `pyscal` could have `ipywidgets` as optional requirements. 

Best, 

Jan 

For future reference https://github.com/pyiron/pyiron_atomistics/pull/819

**Comment by srmnitc** [comment]
@jan-janssen This is not a problem, I can remove ipywidgets as a dependency in pyscal. I will do this and make a new release soon.

**Comment by srmnitc** [comment]
Testing on https://github.com/pyscal/pyscal/pull/132
